### ISSUE TITLE
watch webinars

### ISSUE THREAD

**Issue by MartijnAB** [MartijnAB/UM_BiGCaT_AB#1]
https://cbiit.webex.com/cbiit/ldr.php?RCID=868c32e00641411e0bf775f4b43533e4

**Comment by MartijnAB** [comment]
I have seen the first one.

**Comment by MartijnAB** [comment]
https://cbiit.webex.com/cbiit/ldr.php?RCID=868c32e00641411e0bf775f4b43533e4

**Comment by marvinm2** [comment]
Nano Working Group-20180927 1505-1
--
Thursday, September 27, 2018
12:10 pm  \|  Eastern Daylight Time (New York, GMT-04:00)

**Comment by marvinm2** [comment]
https://cbiit.webex.com/cbiit/ldr.php?RCID=868c32e00641411e0bf775f4b43533e4

**Comment by marvinm2** [comment]
https://drive.google.com/open?id=1gwxWlvZhQyvyiikYEJG5ZMQy8bH2guHh
