### ISSUE TITLE
Contact Graham Dumpleton when issues with jupyter

### ISSUE THREAD

**Issue by marvinm2** [MartijnAB/UM_BiGCaT_AB#12]
We have an active channel open with Graham Dumpleton from Red Hat who is driving this 'Jupyter on Openshift' work. He seems keen to help us with this (see the github issues).

**Comment by MartijnAB** [comment]
imports?
write permissions

**Comment by marvinm2** [comment]
https://github.com/OpenRiskNet/home/tree/master/openshift/deployments/jupyter

Here is more info, and the email of Graham
