### ISSUE TITLE
Write test for bridgedb docker service

### ISSUE THREAD

**Issue by marvinm2** [MartijnAB/UM_BiGCaT_AB#13]
http://bridgedb.prod.openrisknet.org/swagger/

Test for:
GET /{organism}/xrefs/{systemCode}/{identifier} --> All genes of human, mouse, rat
GET /{organism}/xrefExists/{systemCode}/{identifier} --> All genes of human, mouse, rat
GET /{organism}/search/{query} --> All genes of human, mouse, rat
GET /{organism}/properties --> For human, mouse, rat
GET /{organism}/sourceDataSources --> For human, mouse, rat
GET /{organism}/targetDataSources --> For human, mouse, rat
GET /{organism}/isFreeSearchSupported --> For human, mouse, rat
GET /{organism}/isMappingSupported/{sourceSystemCode}/{targetSystemCode} --> All genes of human, mouse, rat
GET /{organism}/attributeSearch/{query} --> Wordt nog bekeken.
GET /{organism}/attributes/{systemCode}/{identifier} --> All genes of human, mouse, rat
GET /{organism}/attributeSet --> For human, mouse, rat

GET /{organ­ism}/xrefs/{systemCode}/{identifier} --> For human as organism, all metabolites
GET /{organism}/attributeSearch/{query} --> Wordt nog bekeken.

**Comment by marvinm2** [comment]
Starting point: retrieve matrix for metabolites and genes.
SPARQL queries for metabolites and genes to test bridgedb.

Metabolites:
SELECT ?metaboliet ?HMDB_identificatiecode ?ChEBI_identificatiecode WHERE {
SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
?metaboliet wdt:P2057 ?HMDB_identificatiecode.
?metaboliet wdt:P683 ?ChEBI_identificatiecode.
}
LIMIT 1000

Human:
SELECT ?gen ?genLabel ?Ensembl_database_identificatiecode  WHERE {
SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
?gen wdt:P31 wd:Q7187.
?gen wdt:P594 ?Ensembl_database_identificatiecode.
}
LIMIT 1000

Mouse:
SELECT ?gen ?genLabel ?NCBI_Entrez_Gene_id ?Ensembl_database_identificatiecode WHERE {
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
  ?gen wdt:P31 wd:Q7187.
  ?gen wdt:P703 wd:Q83310.
  ?gen wdt:P351 ?NCBI_Entrez_Gene_id. 
  ?gen wdt:P594 ?Ensembl_database_identificatiecode. 
}
LIMIT 1000

Rat:
SELECT ?gen ?genLabel ?NCBI_Entrez_Gene_id ?Ensembl_database_identificatiecode WHERE {
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
  ?gen wdt:P31 wd:Q7187.
  ?gen wdt:P703 wd:Q184224.
  ?gen wdt:P351 ?NCBI_Entrez_Gene_id.
  ?gen wdt:P594 ?Ensembl_database_identificatiecode.
}
LIMIT 1000

**Comment by marvinm2** [comment]
We should extend this test with metrics in the output file, such as requests per second. The people in BiGCaT are very curious about the performance on the cloud version of bridgedb

**Comment by marvinm2** [comment]
SELECT ?metaboliet ?HMDB_identificatiecode ?ChEBI_identificatiecode WHERE {
SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
?metaboliet wdt:P2057 ?HMDB_identificatiecode.
?metaboliet wdt:P683 ?ChEBI_identificatiecode.
}

**Comment by MartijnAB** [comment]
I close the issue for now, since we have done the tests.
